### PR TITLE
Update Inspector API

### PR DESCRIPTION
**Pull request by jhermsmeier**
- Added a script to download & build: `npm run generate`
- Updated download URL
- Updated API domain names
- Fixed a test where `error` wouldn't strictly equal `null` (but be `undefined`)
- Updated docs & lib

### CODE REVIEW

**Comment by AndreasMadsen** [comment]
Oh, wow. Thanks for doing this. I can see it was long overdue. I will try to review this soon.

Tell me, did you remove the generated lib and doc files before generating new ones? Sometimes an entire domain is removed and sometimes it is just deprecated. Removing the lib and doc files before generating new ones, can give an idea about what have been removed.

**Comment by AndreasMadsen** [comment]
Awesome, I will have to test this with the [`stear`](https://github.com/AndreasMadsen/steer) stuff before merging, but it looks good.

**Comment by AndreasMadsen** [comment]
@kesla This makes me so happy :)

**Comment by kesla** [comment]
@AndreasMadsen yes, oh yes this is nice!

**Comment by jhermsmeier** [comment]
Alright, I'll fix up the things you mentioned, and will probably generate from the latest sources again, I think I saw they changed a few minor things (docs only, I believe).

> Tell me, did you remove the generated lib and doc files before generating new ones?

Yes - I noticed that when I ran the build the first time.

**Comment by AndreasMadsen** [comment]
Awesome. Thanks for doing this.

**Comment by jhermsmeier** [comment]
Sure, glad I could help :)

**Pull request merged**
